### ISSUE TITLE
Using it on a server

### ISSUE THREAD

**Issue by ValentinJSchmidt** [MaximusMutschler/Virtual-Neural-Style-Transfer-Webcam-for-Linux#2]
Hey,
I really like your project. I am a  Bsc. Student at Tübingen and i am very interested in style-transfer for a Uni project.
 Is it also possible to use these speed-up techniques vor frames or using a remote webcam from a user, while the program runs on the hosting machine? 
I hope my questions aren't to specific ( this is my second public issue ever).
Thank you and keep up the impressive work!
Best,
JoJo

**Comment by MaximusMutschler** [comment]
Hey Jojo, happy to hear that you like my work :)
without changes, it will not work to run this script on a remote server connecting to a webcam on a client.
However, if you look into the details, each frame is style-transferred separately. Thus, if you can manage to stream each frame  to the server and the result back to the client, you can at least reuse the style transfer code. However, this approach might be quite slow in the end.
Just ask if you need some more infos.
Best,
Maximus

**Comment by ValentinJSchmidt** [comment]
Thank you.  I think even the speed increase just by faster style transfer (compared to the pytorch demo) could help me.
Best , 
Valentin 
( I will close this issue later if thats okay, since i might want to ask further questions)
